export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUEST_ERROR = 'ADD_REQUEST_ERROR';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_REQUESTS_ERROR = 'FETCH_REQUESTS_ERROR';
