export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUEST_ERROR = 'ADD_REQUEST_ERROR';
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_ADMIN_REQUESTS = 'FETCH_ADMIN_REQUESTS';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUESTS_ERROR = 'FETCH_REQUESTS_ERROR';
export const FETCH_ADMIN_REQUESTS_ERROR = 'FETCH_ADMIN_REQUESTS_ERROR';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const EDIT_REQUEST = 'EDIT_REQUEST';
export const EDIT_REQUEST_ERROR = 'EDIT_REQUEST_ERROR';
export const MANAGE_ADMIN_REQUEST_APPROVE = 'MANAGE_ADMIN_REQUEST_APPROVE';
export const MANAGE_ADMIN_REQUEST_APPROVE_ERROR =
  'MANAGE_ADMIN_REQUEST_APPROVE_ERROR';
export const MANAGE_ADMIN_REQUEST_DISAPPROVE =
  'MANAGE_ADMIN_REQUEST_DISAPPROVE';
export const MANAGE_ADMIN_REQUEST_DISAPPROVE_ERROR =
  'MANAGE_ADMIN_REQUEST_DISAPPROVE_ERROR';
export const MANAGE_ADMIN_REQUEST_RESOLVE = 'MANAGE_ADMIN_REQUEST_RESOLVE';
export const MANAGE_ADMIN_REQUEST_RESOLVE_ERROR =
  'MANAGE_ADMIN_REQUEST_RESOLVE_ERROR';
